GET http://localhost:3000/

###
GET https://wa-chatbot-production.up.railway.app/

###
GET https://wa-chatbot-production.up.railway.app/webhook?hub.mode=subscribe&hub.challenge=1158201444&hub.verify_token=EAAIT5n8yjKwBOZBIGZC5xrwArMCJlkjqTzajRgZAl0tZCOKafqVoPZAVZCoCW41arHFvTZCBbhmuz5fiZAvH3E7U5jiJofcUfLGm8jItDrUwsZB7ofm22Terk5RrQ2Nkvp8nL99N1YwNJYMmiHFcwUAHxEZCGP8NLrKqZCggdxKkotmJiEH78insMWdiche0aL73UkDbwZDZD

###
GET http://localhost:3000/webhook?hub.mode=subscribe&hub.challenge=1158201444&hub.verify_token=EAAIT5n8yjKwBOZBIGZC5xrwArMCJlkjqTzajRgZAl0tZCOKafqVoPZAVZCoCW41arHFvTZCBbhmuz5fiZAvH3E7U5jiJofcUfLGm8jItDrUwsZB7ofm22Terk5RrQ2Nkvp8nL99N1YwNJYMmiHFcwUAHxEZCGP8NLrKqZCggdxKkotmJiEH78insMWdiche0aL73UkDbwZDZD

###
POST http://localhost:3000/webhook
# POST https://wa-chatbot-production.up.railway.app/webhook
Content-Type: application/json

{
  "field": "messages",
  "value": {
    "messaging_product": "whatsapp",
    "metadata": {
      "display_phone_number": "16505551111",
      "phone_number_id": "123456123"
    },
    "contacts": [
      {
        "profile": {
          "name": "test user name"
        },
        "wa_id": "16315551181"
      }
    ],
    "messages": [
      {
        "from": "16315551181",
        "id": "ABGGFlA5Fpa",
        "timestamp": "1504902988",
        "type": "text",
        "text": {
          "body": "this is a text message"
        }
      }
    ]
  }
}